-- =============================================================================
-- Hospital360 Demo: Roles & Grants
-- =============================================================================
-- Run as: SNOWFLAKE-ILABS-EMERGEPR (has CREATE ROLE from USERADMIN)
-- =============================================================================

USE ROLE "SNOWFLAKE-ILABS-EMERGEPR";

-- =============================================================================
-- SECTION 1: Create Roles
-- =============================================================================

CREATE ROLE IF NOT EXISTS H360_ADMIN
  COMMENT = 'Hospital360: Top-level admin — owns all H360 objects';

CREATE ROLE IF NOT EXISTS H360_ENGINEER
  COMMENT = 'Hospital360: Data engineer — read/write RAW, INT, CUR, ML';

CREATE ROLE IF NOT EXISTS H360_ANALYST
  COMMENT = 'Hospital360: Analyst — read-only CUR + APP, masked PHI';

CREATE ROLE IF NOT EXISTS H360_CLINICIAN
  COMMENT = 'Hospital360: Clinician — read-only CUR + APP, unmasked PHI for patient care';

CREATE ROLE IF NOT EXISTS H360_FINANCE
  COMMENT = 'Hospital360: Finance — read-only CUR.FINANCIAL + CUR.OPERATIONS';

CREATE ROLE IF NOT EXISTS H360_EXEC
  COMMENT = 'Hospital360: Executive — read-only CUR + APP, fully masked PHI';

-- =============================================================================
-- SECTION 2: Role Hierarchy
-- =============================================================================

-- H360_ADMIN inherits all functional roles
GRANT ROLE H360_ENGINEER  TO ROLE H360_ADMIN;
GRANT ROLE H360_ANALYST   TO ROLE H360_ADMIN;
GRANT ROLE H360_CLINICIAN TO ROLE H360_ADMIN;
GRANT ROLE H360_FINANCE   TO ROLE H360_ADMIN;
GRANT ROLE H360_EXEC      TO ROLE H360_ADMIN;

-- H360_ADMIN rolls up to SYSADMIN
GRANT ROLE H360_ADMIN TO ROLE SYSADMIN;

-- Grant H360_ADMIN to our current session role for management
GRANT ROLE H360_ADMIN TO ROLE "SNOWFLAKE-ILABS-EMERGEPR";

-- =============================================================================
-- SECTION 3: Warehouse Grants
-- =============================================================================

-- H360_ADMIN: operate all warehouses
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE H360_LOAD_WH TO ROLE H360_ADMIN;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE H360_XFM_WH  TO ROLE H360_ADMIN;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE H360_BI_WH   TO ROLE H360_ADMIN;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE H360_ML_WH   TO ROLE H360_ADMIN;

-- H360_ENGINEER: load + transform + ML warehouses
GRANT USAGE ON WAREHOUSE H360_LOAD_WH TO ROLE H360_ENGINEER;
GRANT USAGE ON WAREHOUSE H360_XFM_WH  TO ROLE H360_ENGINEER;
GRANT USAGE ON WAREHOUSE H360_ML_WH   TO ROLE H360_ENGINEER;

-- H360_ANALYST, H360_CLINICIAN, H360_FINANCE, H360_EXEC: BI warehouse only
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_ANALYST;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_CLINICIAN;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_FINANCE;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_EXEC;

-- =============================================================================
-- SECTION 4: Database-Level Grants
-- =============================================================================

-- H360_ADMIN: full control on all databases
GRANT ALL PRIVILEGES ON DATABASE HOSPITAL360_RAW TO ROLE H360_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE HOSPITAL360_INT TO ROLE H360_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE HOSPITAL360_CUR TO ROLE H360_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE HOSPITAL360_ML  TO ROLE H360_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE HOSPITAL360_APP TO ROLE H360_ADMIN;

-- H360_ENGINEER: usage on all databases (schema-level grants below)
GRANT USAGE ON DATABASE HOSPITAL360_RAW TO ROLE H360_ENGINEER;
GRANT USAGE ON DATABASE HOSPITAL360_INT TO ROLE H360_ENGINEER;
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;
GRANT USAGE ON DATABASE HOSPITAL360_ML  TO ROLE H360_ENGINEER;

-- H360_ANALYST: read-only on CUR + APP
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT USAGE ON DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;

-- H360_CLINICIAN: read-only on CUR + APP
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT USAGE ON DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;

-- H360_FINANCE: read-only on CUR (limited schemas) + APP
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_FINANCE;
GRANT USAGE ON DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;

-- H360_EXEC: read-only on CUR + APP
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT USAGE ON DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;

-- =============================================================================
-- SECTION 5: Schema-Level Grants — H360_ENGINEER (read-write)
-- =============================================================================

-- RAW: all schemas
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HOSPITAL360_RAW TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_RAW TO ROLE H360_ENGINEER;

-- INT: all schemas
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HOSPITAL360_INT TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_INT TO ROLE H360_ENGINEER;

-- CUR: all schemas
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;

-- ML: all schemas
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE HOSPITAL360_ML TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_ML TO ROLE H360_ENGINEER;

-- Tables/views in RAW, INT, CUR, ML
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HOSPITAL360_RAW TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HOSPITAL360_RAW TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HOSPITAL360_INT TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HOSPITAL360_INT TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE HOSPITAL360_ML  TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE HOSPITAL360_ML  TO ROLE H360_ENGINEER;

GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ENGINEER;

-- =============================================================================
-- SECTION 6: Schema-Level Grants — H360_ANALYST (read-only CUR + APP)
-- =============================================================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_ANALYST;

-- =============================================================================
-- SECTION 7: Schema-Level Grants — H360_CLINICIAN (read-only CUR + APP)
-- =============================================================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_CLINICIAN;

-- =============================================================================
-- SECTION 8: Schema-Level Grants — H360_FINANCE (limited CUR schemas + APP)
-- =============================================================================

-- Finance only gets FINANCIAL and OPERATIONS schemas in CUR
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.FINANCIAL  TO ROLE H360_FINANCE;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL360_CUR.FINANCIAL  TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HOSPITAL360_CUR.FINANCIAL  TO ROLE H360_FINANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;
GRANT SELECT ON ALL VIEWS IN SCHEMA HOSPITAL360_CUR.FINANCIAL  TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HOSPITAL360_CUR.FINANCIAL  TO ROLE H360_FINANCE;
GRANT SELECT ON ALL VIEWS IN SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_FINANCE;

-- =============================================================================
-- SECTION 9: Schema-Level Grants — H360_EXEC (read-only CUR + APP)
-- =============================================================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;
GRANT SELECT ON ALL TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;
GRANT SELECT ON FUTURE TABLES IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;
GRANT SELECT ON ALL VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HOSPITAL360_APP TO ROLE H360_EXEC;

-- =============================================================================
-- SECTION 10: Grant current user all H360 roles for demo purposes
-- =============================================================================

GRANT ROLE H360_ADMIN     TO USER "MIKE.DAMPIER@SLALOM.COM";
GRANT ROLE H360_ENGINEER  TO USER "MIKE.DAMPIER@SLALOM.COM";
GRANT ROLE H360_ANALYST   TO USER "MIKE.DAMPIER@SLALOM.COM";
GRANT ROLE H360_CLINICIAN TO USER "MIKE.DAMPIER@SLALOM.COM";
GRANT ROLE H360_FINANCE   TO USER "MIKE.DAMPIER@SLALOM.COM";
GRANT ROLE H360_EXEC      TO USER "MIKE.DAMPIER@SLALOM.COM";
