-- =============================================================================
-- Hospital360 Demo: Apply Governance — Tags, Masking Policies, RAP Mapping
-- =============================================================================
-- Run as: SYSADMIN (after dimensions/facts seeded, governance objects exist)
-- Prerequisite: 04_governance.sql, 08/09_seed*.sql executed
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE H360_LOAD_WH;

-- =============================================================================
-- SECTION 1: Tag PHI/PII Columns with DATA_CLASSIFICATION and PII_TYPE
-- =============================================================================

-- DIM_PATIENT PHI/PII columns
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN SSN SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PHI',
                             HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'SSN';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN DOB SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PHI',
                             HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'DOB';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN FIRST_NAME SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                                    HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'NAME';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN LAST_NAME SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                                   HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'NAME';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN MRN SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PHI',
                            HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'MRN';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN PHONE SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                              HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'PHONE';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN EMAIL SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                              HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'EMAIL';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN ADDRESS SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                                HOSPITAL360_CUR.GOVERNANCE.PII_TYPE = 'ADDRESS';

-- Domain tags
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'DEMOGRAPHIC',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '7_YEARS';

ALTER TABLE HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'CLINICAL',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '7_YEARS';

ALTER TABLE HOSPITAL360_CUR.FINANCIAL.FCT_CLAIM_LINE
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'CLAIMS',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '7_YEARS';

ALTER TABLE HOSPITAL360_CUR.FINANCIAL.FCT_REMITTANCE
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'FINANCIAL',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '7_YEARS';

ALTER TABLE HOSPITAL360_CUR.WORKFORCE.FCT_LABOR_HOUR
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'WORKFORCE',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '3_YEARS';

ALTER TABLE HOSPITAL360_CUR.SUPPLY_CHAIN.FCT_SUPPLY_USAGE
  SET TAG HOSPITAL360_CUR.GOVERNANCE.DATA_DOMAIN = 'OPERATIONS',
          HOSPITAL360_CUR.GOVERNANCE.RETENTION_POLICY = '3_YEARS';

-- =============================================================================
-- SECTION 2: Attach Masking Policies to PHI/PII Columns
-- =============================================================================

-- SSN masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN SSN SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_SSN;

-- DOB masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN DOB SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_DOB;

-- Patient name masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN FIRST_NAME SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_PATIENT_NAME;

ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN LAST_NAME SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_PATIENT_NAME;

-- MRN masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN MRN SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_MRN;

-- Phone masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN PHONE SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_PHONE;

-- Email masking
ALTER TABLE HOSPITAL360_CUR.CLINICAL.DIM_PATIENT
  MODIFY COLUMN EMAIL SET MASKING POLICY HOSPITAL360_CUR.GOVERNANCE.MASK_EMAIL;

-- =============================================================================
-- SECTION 3: Populate Row-Access Policy Mapping Tables
-- =============================================================================

-- Clear and repopulate
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.GOVERNANCE.ROLE_DEPT_ACCESS;
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.GOVERNANCE.ROLE_FACILITY_ACCESS;

-- H360_CLINICIAN: all clinical departments
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_DEPT_ACCESS (ROLE_NAME, DEPT_ID, COMMENT)
SELECT 'H360_CLINICIAN', DEPT_ID, 'Clinician access to all departments'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT;

-- H360_ANALYST: all departments (analytics)
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_DEPT_ACCESS (ROLE_NAME, DEPT_ID, COMMENT)
SELECT 'H360_ANALYST', DEPT_ID, 'Analyst access to all departments'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT;

-- H360_FINANCE: only financial-related departments (Med-Surg, OR, etc.)
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_DEPT_ACCESS (ROLE_NAME, DEPT_ID, COMMENT)
VALUES
    ('H360_FINANCE', 'DEPT-004', 'Finance: Med-Surg 4N'),
    ('H360_FINANCE', 'DEPT-005', 'Finance: Med-Surg 4S'),
    ('H360_FINANCE', 'DEPT-011', 'Finance: OR'),
    ('H360_FINANCE', 'DEPT-019', 'Finance: Med-Surg Northgate'),
    ('H360_FINANCE', 'DEPT-024', 'Finance: Med-Surg Eastside');

-- H360_EXEC: all departments
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_DEPT_ACCESS (ROLE_NAME, DEPT_ID, COMMENT)
SELECT 'H360_EXEC', DEPT_ID, 'Executive access to all departments'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT;

-- Facility access
-- H360_CLINICIAN: all owned facilities
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_FACILITY_ACCESS (ROLE_NAME, FACILITY_ID, COMMENT)
SELECT 'H360_CLINICIAN', FACILITY_ID, 'Clinician access to all facilities'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY;

-- H360_ANALYST: all facilities
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_FACILITY_ACCESS (ROLE_NAME, FACILITY_ID, COMMENT)
SELECT 'H360_ANALYST', FACILITY_ID, 'Analyst access to all facilities'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY;

-- H360_FINANCE: only main hospital and community hospitals
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_FACILITY_ACCESS (ROLE_NAME, FACILITY_ID, COMMENT)
VALUES
    ('H360_FINANCE', 'FAC-001', 'Finance: Main hospital'),
    ('H360_FINANCE', 'FAC-002', 'Finance: Northgate'),
    ('H360_FINANCE', 'FAC-003', 'Finance: Eastside');

-- H360_EXEC: all facilities
INSERT INTO HOSPITAL360_CUR.GOVERNANCE.ROLE_FACILITY_ACCESS (ROLE_NAME, FACILITY_ID, COMMENT)
SELECT 'H360_EXEC', FACILITY_ID, 'Executive access to all facilities'
FROM HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY;

-- =============================================================================
-- SECTION 4: Attach Row-Access Policies to fact tables with DEPT_ID
-- =============================================================================
-- Note: RAPs are attached to tables that have DEPT_ID or FACILITY_ID columns

ALTER TABLE HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER
  ADD ROW ACCESS POLICY HOSPITAL360_CUR.GOVERNANCE.RAP_DEPARTMENT ON (DEPT_ID);

ALTER TABLE HOSPITAL360_CUR.OPERATIONS.FCT_ADT_EVENT
  ADD ROW ACCESS POLICY HOSPITAL360_CUR.GOVERNANCE.RAP_DEPARTMENT ON (DEPT_ID);

ALTER TABLE HOSPITAL360_CUR.OPERATIONS.FCT_OR_CASE
  ADD ROW ACCESS POLICY HOSPITAL360_CUR.GOVERNANCE.RAP_FACILITY ON (FACILITY_ID);

ALTER TABLE HOSPITAL360_CUR.WORKFORCE.FCT_LABOR_HOUR
  ADD ROW ACCESS POLICY HOSPITAL360_CUR.GOVERNANCE.RAP_DEPARTMENT ON (DEPT_ID);

ALTER TABLE HOSPITAL360_CUR.OPERATIONS.FCT_BED_STATUS
  ADD ROW ACCESS POLICY HOSPITAL360_CUR.GOVERNANCE.RAP_DEPARTMENT ON (DEPT_ID);
