-- =============================================================================
-- Hospital360 Demo: Populate Use-Case Marts (Week 3 — UCs 1-4)
-- =============================================================================
-- Run as: SYSADMIN on H360_XFM_WH
-- Prerequisite: 11_mart_ddls.sql executed, all dims/facts populated
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE H360_XFM_WH;

-- =============================================================================
-- UC1: MART_PATIENT_LEAKAGE
-- Source: FCT_REFERRAL + DIM_PATIENT + DIM_PROVIDER + DIM_PAYER + DIM_FACILITY
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE;

INSERT INTO HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE
    (REFERRAL_ID, MRN, PATIENT_NAME, PATIENT_ZIP, PATIENT_PAYER_TYPE,
     REFERRING_PROVIDER_SK, REFERRING_PROVIDER, REFERRING_SPECIALTY,
     REFERRED_TO_NPI, REFERRED_TO_SPECIALTY,
     FACILITY_ID, FACILITY_NAME,
     REFERRAL_DATE, REFERRAL_MONTH, REFERRAL_QUARTER,
     STATUS, LEAKAGE_FLAG, EXPECTED_REVENUE, LOST_REVENUE,
     DAYS_SINCE_REFERRAL, IS_HIGH_VALUE)
SELECT
    r.REFERRAL_ID,
    p.MRN,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    p.ZIP AS PATIENT_ZIP,
    py.PAYER_TYPE AS PATIENT_PAYER_TYPE,
    r.REFERRING_PROVIDER_SK,
    prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL AS REFERRING_PROVIDER,
    prov.SPECIALTY AS REFERRING_SPECIALTY,
    r.REFERRED_TO_NPI,
    r.REFERRED_TO_SPECIALTY,
    r.FACILITY_ID,
    f.FACILITY_NAME,
    r.REFERRAL_DATE,
    DATE_TRUNC('MONTH', r.REFERRAL_DATE) AS REFERRAL_MONTH,
    YEAR(r.REFERRAL_DATE)::STRING || '-Q' || QUARTER(r.REFERRAL_DATE)::STRING AS REFERRAL_QUARTER,
    r.STATUS,
    r.LEAKAGE_FLAG,
    r.EXPECTED_REVENUE,
    CASE WHEN r.LEAKAGE_FLAG THEN r.EXPECTED_REVENUE ELSE 0 END AS LOST_REVENUE,
    DATEDIFF(DAY, r.REFERRAL_DATE, CURRENT_DATE()) AS DAYS_SINCE_REFERRAL,
    r.EXPECTED_REVENUE > 5000 AS IS_HIGH_VALUE
FROM HOSPITAL360_CUR.CLINICAL.FCT_REFERRAL r
JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT p ON p.PATIENT_SK = r.PATIENT_SK
JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = r.REFERRING_PROVIDER_SK
LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_ID = p.PRIMARY_PAYER_ID
LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = r.FACILITY_ID;

-- =============================================================================
-- UC2: MART_READMISSION_LOS
-- Source: FCT_ENCOUNTER + DIM_PATIENT + DIM_PROVIDER + DIM_DRG + DIM_PAYER
--         + DIM_DEPARTMENT + DIM_FACILITY
-- Filter: INPATIENT and OBSERVATION encounters only
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS;

INSERT INTO HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS
    (ENCOUNTER_ID, MRN, PATIENT_NAME, PATIENT_AGE, PATIENT_GENDER, HCC_SCORE,
     ADMIT_DATE, ADMIT_MONTH, DISCHARGE_DATE, DISCHARGE_DISPOSITION, ENCOUNTER_TYPE,
     LOS_DAYS, EXPECTED_LOS, LOS_VARIANCE, LOS_INDEX, IS_LONG_STAY,
     DRG_CODE, DRG_DESCRIPTION, DRG_WEIGHT, MDC_DESCRIPTION,
     READMIT_30_FLAG, PAYER_TYPE, PAYER_NAME,
     FACILITY_ID, FACILITY_NAME, DEPT_ID, DEPT_NAME,
     ATTENDING_PROVIDER, SPECIALTY,
     TOTAL_CHARGES, TOTAL_COST, TOTAL_PAYMENTS, COST_PER_DAY, NET_REVENUE)
SELECT
    e.ENCOUNTER_ID,
    p.MRN,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    DATEDIFF(YEAR, p.DOB, e.ADMIT_DATE) AS PATIENT_AGE,
    p.GENDER AS PATIENT_GENDER,
    p.HCC_SCORE,
    e.ADMIT_DATE,
    DATE_TRUNC('MONTH', e.ADMIT_DATE) AS ADMIT_MONTH,
    e.DISCHARGE_DATE,
    e.DISCHARGE_DISPOSITION,
    e.ENCOUNTER_TYPE,
    e.LOS_DAYS,
    COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) AS EXPECTED_LOS,
    e.LOS_DAYS - COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) AS LOS_VARIANCE,
    CASE WHEN COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 0
         THEN ROUND(e.LOS_DAYS / COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS), 2)
         ELSE NULL END AS LOS_INDEX,
    CASE WHEN COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 0
              AND e.LOS_DAYS / COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 1.5
         THEN TRUE ELSE FALSE END AS IS_LONG_STAY,
    drg.DRG_CODE,
    drg.DESCRIPTION AS DRG_DESCRIPTION,
    drg.WEIGHT AS DRG_WEIGHT,
    drg.MDC_DESCRIPTION,
    e.READMIT_30_FLAG,
    py.PAYER_TYPE,
    py.PAYER_NAME,
    e.FACILITY_ID,
    f.FACILITY_NAME,
    e.DEPT_ID,
    d.DEPT_NAME,
    prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL AS ATTENDING_PROVIDER,
    prov.SPECIALTY,
    e.TOTAL_CHARGES,
    e.TOTAL_COST,
    e.TOTAL_PAYMENTS,
    CASE WHEN e.LOS_DAYS > 0 THEN ROUND(e.TOTAL_COST / e.LOS_DAYS, 2) ELSE e.TOTAL_COST END AS COST_PER_DAY,
    e.NET_REVENUE
FROM HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER e
JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT p ON p.PATIENT_SK = e.PATIENT_SK
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = e.PROVIDER_SK
LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_DRG drg ON drg.DRG_SK = e.DRG_SK
LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_SK = e.PAYER_SK
LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT d ON d.DEPT_ID = e.DEPT_ID
LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = e.FACILITY_ID
WHERE e.ENCOUNTER_TYPE IN ('INPATIENT', 'OBSERVATION');

-- =============================================================================
-- UC3: MART_OR_CAPACITY
-- Source: FCT_OR_CASE + DIM_PROVIDER (surgeon) + DIM_FACILITY + DIM_PROCEDURE_CPT
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY;

INSERT INTO HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY
    (CASE_ID, ENCOUNTER_ID, OR_ROOM_ID, FACILITY_ID, FACILITY_NAME,
     SURGEON_SK, SURGEON_NAME, SPECIALTY, BLOCK_NAME,
     CASE_DATE, CASE_MONTH, CASE_DAY_OF_WEEK,
     SCHEDULED_START, ACTUAL_START, ACTUAL_END,
     DELAY_MINUTES, CASE_MINUTES, TURNOVER_MINUTES, BLOCK_MINUTES,
     UTILIZATION_PCT, FIRST_CASE_ON_TIME, PRIME_TIME_FLAG,
     CASE_CLASS, ASA_CLASS, CPT_CODE, CPT_DESCRIPTION,
     IS_UNDERUTILIZED, IS_OVERTIME)
SELECT
    orc.CASE_ID,
    orc.ENCOUNTER_ID,
    orc.OR_ROOM_ID,
    orc.FACILITY_ID,
    f.FACILITY_NAME,
    orc.SURGEON_SK,
    prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL AS SURGEON_NAME,
    prov.SPECIALTY,
    orc.BLOCK_NAME,
    orc.CASE_DATE,
    DATE_TRUNC('MONTH', orc.CASE_DATE) AS CASE_MONTH,
    DAYNAME(orc.CASE_DATE) AS CASE_DAY_OF_WEEK,
    orc.SCHEDULED_START,
    orc.ACTUAL_START,
    orc.ACTUAL_END,
    DATEDIFF(MINUTE, orc.SCHEDULED_START, orc.ACTUAL_START) AS DELAY_MINUTES,
    orc.CASE_MINUTES,
    orc.TURNOVER_MINUTES,
    orc.BLOCK_MINUTES,
    CASE WHEN orc.BLOCK_MINUTES > 0
         THEN ROUND(orc.CASE_MINUTES / orc.BLOCK_MINUTES, 3)
         ELSE NULL END AS UTILIZATION_PCT,
    orc.FIRST_CASE_ON_TIME,
    orc.PRIME_TIME_FLAG,
    orc.CASE_CLASS,
    orc.ASA_CLASS,
    cpt.CPT_CODE,
    cpt.DESCRIPTION AS CPT_DESCRIPTION,
    CASE WHEN orc.BLOCK_MINUTES > 0 AND orc.CASE_MINUTES / orc.BLOCK_MINUTES < 0.60
         THEN TRUE ELSE FALSE END AS IS_UNDERUTILIZED,
    CASE WHEN HOUR(orc.ACTUAL_END) >= 17 THEN TRUE ELSE FALSE END AS IS_OVERTIME
FROM HOSPITAL360_CUR.OPERATIONS.FCT_OR_CASE orc
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = orc.SURGEON_SK
LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = orc.FACILITY_ID
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROCEDURE_CPT cpt ON cpt.PROC_SK = orc.PRIMARY_CPT_SK;

-- =============================================================================
-- UC4: MART_DENIALS_REVCYCLE
-- Source: FCT_CLAIM_LINE (denied) + DIM_PAYER + DIM_PATIENT + DIM_PROVIDER
--         + DIM_PROCEDURE_CPT + DIM_DIAGNOSIS_ICD10
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE;

INSERT INTO HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE
    (CLAIM_LINE_SK, CLAIM_ID, LINE_NUMBER, ENCOUNTER_ID, MRN, PATIENT_NAME,
     PAYER_SK, PAYER_NAME, PAYER_TYPE, PROVIDER_NAME,
     SERVICE_DATE, SERVICE_MONTH, CHARGE_AMT, ALLOWED_AMT,
     DENIAL_REASON, DENIAL_CATEGORY, CLAIM_STATUS, IS_APPEALED, APPEAL_OUTCOME,
     CPT_CODE, CPT_DESCRIPTION, CPT_CATEGORY,
     ICD10_CODE, DX_DESCRIPTION,
     FILING_DATE, DAYS_TO_FILE, TIMELY_FILING_LIMIT, IS_TIMELY_FILED,
     ESTIMATED_RECOVERY)
SELECT
    cl.CLAIM_LINE_SK,
    cl.CLAIM_ID,
    cl.LINE_NUMBER,
    cl.ENCOUNTER_ID,
    pt.MRN,
    pt.FIRST_NAME || ' ' || pt.LAST_NAME AS PATIENT_NAME,
    cl.PAYER_SK,
    py.PAYER_NAME,
    py.PAYER_TYPE,
    prov.FIRST_NAME || ' ' || prov.LAST_NAME AS PROVIDER_NAME,
    cl.SERVICE_DATE,
    DATE_TRUNC('MONTH', cl.SERVICE_DATE) AS SERVICE_MONTH,
    cl.CHARGE_AMT,
    cl.ALLOWED_AMT,
    cl.DENIAL_REASON,
    -- Map denial reasons to broader categories
    CASE
        WHEN cl.DENIAL_REASON = 'ELIGIBILITY'        THEN 'ELIGIBILITY & ENROLLMENT'
        WHEN cl.DENIAL_REASON = 'AUTH_REQUIRED'       THEN 'PRIOR AUTHORIZATION'
        WHEN cl.DENIAL_REASON = 'CODING_ERROR'        THEN 'CODING & BILLING'
        WHEN cl.DENIAL_REASON = 'MEDICAL_NECESSITY'   THEN 'CLINICAL / MEDICAL NECESSITY'
        ELSE 'OTHER'
    END AS DENIAL_CATEGORY,
    cl.CLAIM_STATUS,
    cl.CLAIM_STATUS = 'APPEALED' AS IS_APPEALED,
    CASE
        WHEN cl.CLAIM_STATUS = 'APPEALED' AND ABS(MOD(HASH(cl.CLAIM_ID), 100)) < 40
            THEN 'WON'
        WHEN cl.CLAIM_STATUS = 'APPEALED'
            THEN 'LOST'
        WHEN cl.CLAIM_STATUS = 'DENIED'
            THEN 'NOT_APPEALED'
        ELSE 'PENDING'
    END AS APPEAL_OUTCOME,
    cpt.CPT_CODE,
    cpt.DESCRIPTION AS CPT_DESCRIPTION,
    cpt.CATEGORY AS CPT_CATEGORY,
    dx.ICD10_CODE,
    dx.DESCRIPTION AS DX_DESCRIPTION,
    cl.FILING_DATE,
    DATEDIFF(DAY, cl.SERVICE_DATE, cl.FILING_DATE) AS DAYS_TO_FILE,
    py.TIMELY_FILING_DAYS AS TIMELY_FILING_LIMIT,
    CASE WHEN py.TIMELY_FILING_DAYS IS NOT NULL
              AND DATEDIFF(DAY, cl.SERVICE_DATE, cl.FILING_DATE) <= py.TIMELY_FILING_DAYS
         THEN TRUE ELSE FALSE END AS IS_TIMELY_FILED,
    -- Estimated recovery based on denial category appeal success rates
    ROUND(cl.CHARGE_AMT * CASE
        WHEN cl.DENIAL_REASON = 'ELIGIBILITY'        THEN 0.30  -- 30% recovery rate
        WHEN cl.DENIAL_REASON = 'AUTH_REQUIRED'       THEN 0.50  -- 50% recovery rate
        WHEN cl.DENIAL_REASON = 'CODING_ERROR'        THEN 0.65  -- 65% recovery rate (refile)
        WHEN cl.DENIAL_REASON = 'MEDICAL_NECESSITY'   THEN 0.35  -- 35% recovery rate
        ELSE 0.20
    END, 2) AS ESTIMATED_RECOVERY
FROM HOSPITAL360_CUR.FINANCIAL.FCT_CLAIM_LINE cl
JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT pt ON pt.PATIENT_SK = cl.PATIENT_SK
JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_SK = cl.PAYER_SK
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = cl.PROVIDER_SK
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROCEDURE_CPT cpt ON cpt.PROC_SK = cl.PROC_SK
LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_DIAGNOSIS_ICD10 dx ON dx.DX_SK = cl.DX_SK
WHERE cl.DENIED_FLAG = TRUE;

-- =============================================================================
-- UC5: MART_STAFFING_QUALITY
-- Source: FCT_LABOR_HOUR + FCT_ENCOUNTER + DIM_DEPARTMENT + DIM_FACILITY
-- Grain: 1 row per department per day
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.WORKFORCE.MART_STAFFING_QUALITY;

INSERT INTO HOSPITAL360_CUR.WORKFORCE.MART_STAFFING_QUALITY
    (DEPT_ID, DEPT_NAME, DEPT_TYPE, FACILITY_ID, FACILITY_NAME,
     SHIFT_DATE, SHIFT_MONTH, DAY_OF_WEEK,
     TOTAL_WORKED_HRS, TOTAL_OT_HRS, OT_PCT, TOTAL_LABOR_COST,
     STAFF_COUNT, AGENCY_STAFF_COUNT, AGENCY_PCT,
     PATIENT_CENSUS, HRS_PER_PATIENT, ADMITS, DISCHARGES,
     READMIT_COUNT, READMIT_RATE, AVG_LOS_DAYS, AVG_LOS_INDEX, LONG_STAY_COUNT,
     IS_UNDERSTAFFED, HIGH_OT_FLAG)
WITH labor_daily AS (
    SELECT
        DEPT_ID,
        FACILITY_ID,
        SHIFT_DATE,
        SUM(WORKED_HRS)                                      AS TOTAL_WORKED_HRS,
        SUM(OT_HRS)                                          AS TOTAL_OT_HRS,
        CASE WHEN SUM(WORKED_HRS) > 0
             THEN ROUND(SUM(OT_HRS) / SUM(WORKED_HRS), 3)
             ELSE 0 END                                      AS OT_PCT,
        SUM(TOTAL_LABOR_COST)                                AS TOTAL_LABOR_COST,
        COUNT(DISTINCT EMPLOYEE_ID)                           AS STAFF_COUNT,
        COUNT(DISTINCT CASE WHEN AGENCY_FLAG THEN EMPLOYEE_ID END) AS AGENCY_STAFF_COUNT
    FROM HOSPITAL360_CUR.WORKFORCE.FCT_LABOR_HOUR
    GROUP BY DEPT_ID, FACILITY_ID, SHIFT_DATE
),
census_daily AS (
    SELECT
        DEPT_ID,
        FACILITY_ID,
        d.FULL_DATE AS CENSUS_DATE,
        COUNT(DISTINCT e.ENCOUNTER_ID)                        AS PATIENT_CENSUS,
        COUNT(DISTINCT CASE WHEN e.ADMIT_DATE = d.FULL_DATE THEN e.ENCOUNTER_ID END) AS ADMITS,
        COUNT(DISTINCT CASE WHEN e.DISCHARGE_DATE = d.FULL_DATE THEN e.ENCOUNTER_ID END) AS DISCHARGES,
        COUNT(DISTINCT CASE WHEN e.DISCHARGE_DATE = d.FULL_DATE AND e.READMIT_30_FLAG
              THEN e.ENCOUNTER_ID END)                        AS READMIT_COUNT,
        AVG(e.LOS_DAYS)                                       AS AVG_LOS_DAYS,
        AVG(CASE WHEN e.EXPECTED_LOS > 0 THEN e.LOS_DAYS / e.EXPECTED_LOS END) AS AVG_LOS_INDEX,
        COUNT(DISTINCT CASE WHEN e.EXPECTED_LOS > 0
              AND e.LOS_DAYS / e.EXPECTED_LOS > 1.5
              AND e.DISCHARGE_DATE = d.FULL_DATE
              THEN e.ENCOUNTER_ID END)                        AS LONG_STAY_COUNT
    FROM HOSPITAL360_CUR.CLINICAL.DIM_DATE d
    JOIN HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER e
        ON d.FULL_DATE BETWEEN e.ADMIT_DATE AND COALESCE(e.DISCHARGE_DATE, d.FULL_DATE)
        AND e.ENCOUNTER_TYPE IN ('INPATIENT', 'OBSERVATION')
    WHERE d.FULL_DATE BETWEEN '2023-07-01' AND '2024-12-30'
    GROUP BY e.DEPT_ID, e.FACILITY_ID, d.FULL_DATE
)
SELECT
    l.DEPT_ID,
    dep.DEPT_NAME,
    dep.DEPT_TYPE,
    l.FACILITY_ID,
    f.FACILITY_NAME,
    l.SHIFT_DATE,
    DATE_TRUNC('MONTH', l.SHIFT_DATE)                        AS SHIFT_MONTH,
    DAYNAME(l.SHIFT_DATE)                                    AS DAY_OF_WEEK,
    l.TOTAL_WORKED_HRS,
    l.TOTAL_OT_HRS,
    l.OT_PCT,
    l.TOTAL_LABOR_COST,
    l.STAFF_COUNT,
    l.AGENCY_STAFF_COUNT,
    CASE WHEN l.STAFF_COUNT > 0
         THEN ROUND(l.AGENCY_STAFF_COUNT::FLOAT / l.STAFF_COUNT, 3)
         ELSE 0 END                                          AS AGENCY_PCT,
    COALESCE(c.PATIENT_CENSUS, 0)                            AS PATIENT_CENSUS,
    CASE WHEN COALESCE(c.PATIENT_CENSUS, 0) > 0
         THEN ROUND(l.TOTAL_WORKED_HRS / c.PATIENT_CENSUS, 2)
         ELSE NULL END                                       AS HRS_PER_PATIENT,
    COALESCE(c.ADMITS, 0)                                    AS ADMITS,
    COALESCE(c.DISCHARGES, 0)                                AS DISCHARGES,
    COALESCE(c.READMIT_COUNT, 0)                             AS READMIT_COUNT,
    CASE WHEN COALESCE(c.DISCHARGES, 0) > 0
         THEN ROUND(c.READMIT_COUNT::FLOAT / c.DISCHARGES, 3)
         ELSE NULL END                                       AS READMIT_RATE,
    c.AVG_LOS_DAYS,
    c.AVG_LOS_INDEX,
    COALESCE(c.LONG_STAY_COUNT, 0)                           AS LONG_STAY_COUNT,
    -- Understaffed: < 8 hrs/patient for inpatient/ICU, < 4 for others
    CASE WHEN COALESCE(c.PATIENT_CENSUS, 0) > 0 THEN
        CASE WHEN dep.DEPT_TYPE IN ('INPATIENT', 'ICU')
                  AND l.TOTAL_WORKED_HRS / c.PATIENT_CENSUS < 8 THEN TRUE
             WHEN dep.DEPT_TYPE NOT IN ('INPATIENT', 'ICU')
                  AND l.TOTAL_WORKED_HRS / c.PATIENT_CENSUS < 4 THEN TRUE
             ELSE FALSE END
    ELSE FALSE END                                           AS IS_UNDERSTAFFED,
    l.OT_PCT > 0.15                                          AS HIGH_OT_FLAG
FROM labor_daily l
JOIN HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT dep ON dep.DEPT_ID = l.DEPT_ID
JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = l.FACILITY_ID
LEFT JOIN census_daily c ON c.DEPT_ID = l.DEPT_ID
    AND c.FACILITY_ID = l.FACILITY_ID
    AND c.CENSUS_DATE = l.SHIFT_DATE;

-- =============================================================================
-- UC6: MART_FINANCIAL_PERFORMANCE
-- Source: FCT_GL_TRANSACTION + FCT_ENCOUNTER + DIM_DEPARTMENT + DIM_FACILITY
-- Grain: 1 row per department per fiscal period (month)
-- =============================================================================
TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.FINANCIAL.MART_FINANCIAL_PERFORMANCE;

INSERT INTO HOSPITAL360_CUR.FINANCIAL.MART_FINANCIAL_PERFORMANCE
    (DEPT_ID, DEPT_NAME, DEPT_TYPE, FACILITY_ID, FACILITY_NAME,
     FISCAL_YEAR, FISCAL_PERIOD, PERIOD_DATE,
     TOTAL_REVENUE, LABOR_COST, SUPPLY_COST, OVERHEAD_COST, DEPRECIATION_COST, TOTAL_EXPENSE,
     DISCHARGES, PATIENT_DAYS, CMI_ADJUSTED_DISCHARGES,
     COST_PER_DISCHARGE, COST_PER_CMI_DISCHARGE, LABOR_PCT, SUPPLY_PCT,
     OPERATING_MARGIN, NET_REVENUE, IS_NEGATIVE_MARGIN)
WITH gl_monthly AS (
    SELECT
        DEPT_ID,
        FACILITY_ID,
        FISCAL_YEAR,
        FISCAL_PERIOD,
        SUM(CASE WHEN CATEGORY = 'REVENUE' THEN AMOUNT ELSE 0 END) AS TOTAL_REVENUE,
        SUM(CASE WHEN CATEGORY = 'LABOR' THEN AMOUNT ELSE 0 END)   AS LABOR_COST,
        SUM(CASE WHEN CATEGORY = 'SUPPLIES' THEN AMOUNT ELSE 0 END) AS SUPPLY_COST,
        SUM(CASE WHEN CATEGORY = 'OVERHEAD' THEN AMOUNT ELSE 0 END) AS OVERHEAD_COST,
        SUM(CASE WHEN CATEGORY = 'DEPRECIATION' THEN AMOUNT ELSE 0 END) AS DEPRECIATION_COST
    FROM HOSPITAL360_CUR.FINANCIAL.FCT_GL_TRANSACTION
    WHERE DEPT_ID IS NOT NULL
    GROUP BY DEPT_ID, FACILITY_ID, FISCAL_YEAR, FISCAL_PERIOD
),
volume_monthly AS (
    SELECT
        DEPT_ID,
        FACILITY_ID,
        YEAR(DISCHARGE_DATE)  AS FISCAL_YEAR,
        MONTH(DISCHARGE_DATE) AS FISCAL_PERIOD,
        COUNT(*)              AS DISCHARGES,
        SUM(LOS_DAYS)         AS PATIENT_DAYS,
        SUM(COALESCE(drg.WEIGHT, 1.0)) AS CMI_ADJUSTED_DISCHARGES
    FROM HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER e
    LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_DRG drg ON drg.DRG_SK = e.DRG_SK
    WHERE e.DISCHARGE_DATE IS NOT NULL
      AND e.ENCOUNTER_TYPE IN ('INPATIENT', 'OBSERVATION')
    GROUP BY e.DEPT_ID, e.FACILITY_ID, YEAR(e.DISCHARGE_DATE), MONTH(e.DISCHARGE_DATE)
)
SELECT
    g.DEPT_ID,
    dep.DEPT_NAME,
    dep.DEPT_TYPE,
    g.FACILITY_ID,
    f.FACILITY_NAME,
    g.FISCAL_YEAR,
    g.FISCAL_PERIOD,
    DATE_FROM_PARTS(g.FISCAL_YEAR, g.FISCAL_PERIOD, 1) AS PERIOD_DATE,
    g.TOTAL_REVENUE,
    g.LABOR_COST,
    g.SUPPLY_COST,
    g.OVERHEAD_COST,
    g.DEPRECIATION_COST,
    (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) AS TOTAL_EXPENSE,
    COALESCE(v.DISCHARGES, 0)                          AS DISCHARGES,
    COALESCE(v.PATIENT_DAYS, 0)                        AS PATIENT_DAYS,
    COALESCE(v.CMI_ADJUSTED_DISCHARGES, 0)             AS CMI_ADJUSTED_DISCHARGES,
    CASE WHEN COALESCE(v.DISCHARGES, 0) > 0
         THEN ROUND((g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) / v.DISCHARGES, 2)
         ELSE NULL END                                 AS COST_PER_DISCHARGE,
    CASE WHEN COALESCE(v.CMI_ADJUSTED_DISCHARGES, 0) > 0
         THEN ROUND((g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) / v.CMI_ADJUSTED_DISCHARGES, 2)
         ELSE NULL END                                 AS COST_PER_CMI_DISCHARGE,
    CASE WHEN (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) > 0
         THEN ROUND(g.LABOR_COST / (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST), 3)
         ELSE NULL END                                 AS LABOR_PCT,
    CASE WHEN (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) > 0
         THEN ROUND(g.SUPPLY_COST / (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST), 3)
         ELSE NULL END                                 AS SUPPLY_PCT,
    CASE WHEN g.TOTAL_REVENUE > 0
         THEN ROUND((g.TOTAL_REVENUE - (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST)) / g.TOTAL_REVENUE, 3)
         ELSE NULL END                                 AS OPERATING_MARGIN,
    g.TOTAL_REVENUE - (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST) AS NET_REVENUE,
    (g.TOTAL_REVENUE - (g.LABOR_COST + g.SUPPLY_COST + g.OVERHEAD_COST + g.DEPRECIATION_COST)) < 0 AS IS_NEGATIVE_MARGIN
FROM gl_monthly g
JOIN HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT dep ON dep.DEPT_ID = g.DEPT_ID
JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = g.FACILITY_ID
LEFT JOIN volume_monthly v ON v.DEPT_ID = g.DEPT_ID
    AND v.FACILITY_ID = g.FACILITY_ID
    AND v.FISCAL_YEAR = g.FISCAL_YEAR
    AND v.FISCAL_PERIOD = g.FISCAL_PERIOD;
