/*==============================================================================
  HOSPITAL 360 — Week 6: Cortex Analyst Configuration
  Grants & validation for Cortex Analyst integration
  
  Grants SELECT on underlying tables and USAGE on semantic view
  to all 4 H360 roles so Cortex Analyst-generated SQL can execute.
==============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE H360_BI_WH;

-- ============================================================================
-- 1. GRANT SELECT on CUR mart tables (needed for Cortex Analyst queries)
-- ============================================================================

-- UC2: Readmission & LOS
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS TO ROLE H360_FINANCE;

-- UC1: Patient Leakage
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE TO ROLE H360_FINANCE;

-- UC3: OR Capacity
GRANT SELECT ON TABLE HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY TO ROLE H360_FINANCE;

-- UC4: Denials & Revenue Cycle
GRANT SELECT ON TABLE HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE TO ROLE H360_FINANCE;

-- ML: Predictions
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_ENCOUNTER_VOLUME TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_ENCOUNTER_VOLUME TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_ENCOUNTER_VOLUME TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_ENCOUNTER_VOLUME TO ROLE H360_FINANCE;

GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES TO ROLE H360_ANALYST;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES TO ROLE H360_CLINICIAN;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES TO ROLE H360_EXEC;
GRANT SELECT ON TABLE HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES TO ROLE H360_FINANCE;

-- ============================================================================
-- 2. GRANT USAGE on database/schema/warehouse for H360 roles
-- ============================================================================

-- Database USAGE (may already exist, idempotent)
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_ANALYST;
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_CLINICIAN;
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_EXEC;
GRANT USAGE ON DATABASE HOSPITAL360_CUR TO ROLE H360_FINANCE;

GRANT USAGE ON DATABASE HOSPITAL360_ML TO ROLE H360_ANALYST;
GRANT USAGE ON DATABASE HOSPITAL360_ML TO ROLE H360_CLINICIAN;
GRANT USAGE ON DATABASE HOSPITAL360_ML TO ROLE H360_EXEC;
GRANT USAGE ON DATABASE HOSPITAL360_ML TO ROLE H360_FINANCE;

-- Schema USAGE
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.CLINICAL TO ROLE H360_ANALYST;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.CLINICAL TO ROLE H360_CLINICIAN;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.CLINICAL TO ROLE H360_EXEC;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.CLINICAL TO ROLE H360_FINANCE;

GRANT USAGE ON SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_ANALYST;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_CLINICIAN;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_EXEC;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.OPERATIONS TO ROLE H360_FINANCE;

GRANT USAGE ON SCHEMA HOSPITAL360_CUR.FINANCIAL TO ROLE H360_ANALYST;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.FINANCIAL TO ROLE H360_CLINICIAN;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.FINANCIAL TO ROLE H360_EXEC;
GRANT USAGE ON SCHEMA HOSPITAL360_CUR.FINANCIAL TO ROLE H360_FINANCE;

GRANT USAGE ON SCHEMA HOSPITAL360_ML.PREDICTIONS TO ROLE H360_ANALYST;
GRANT USAGE ON SCHEMA HOSPITAL360_ML.PREDICTIONS TO ROLE H360_CLINICIAN;
GRANT USAGE ON SCHEMA HOSPITAL360_ML.PREDICTIONS TO ROLE H360_EXEC;
GRANT USAGE ON SCHEMA HOSPITAL360_ML.PREDICTIONS TO ROLE H360_FINANCE;

-- Warehouse USAGE
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_ANALYST;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_CLINICIAN;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_EXEC;
GRANT USAGE ON WAREHOUSE H360_BI_WH TO ROLE H360_FINANCE;

-- ============================================================================
-- 3. GRANT USAGE on Semantic View
-- ============================================================================

-- Note: Semantic views use SELECT (not USAGE) for access
GRANT SELECT ON SEMANTIC VIEW HOSPITAL360_APP.SEMANTIC_VIEWS.HOSPITAL360_ANALYTICS
    TO ROLE H360_ANALYST;
GRANT SELECT ON SEMANTIC VIEW HOSPITAL360_APP.SEMANTIC_VIEWS.HOSPITAL360_ANALYTICS
    TO ROLE H360_CLINICIAN;
GRANT SELECT ON SEMANTIC VIEW HOSPITAL360_APP.SEMANTIC_VIEWS.HOSPITAL360_ANALYTICS
    TO ROLE H360_EXEC;
GRANT SELECT ON SEMANTIC VIEW HOSPITAL360_APP.SEMANTIC_VIEWS.HOSPITAL360_ANALYTICS
    TO ROLE H360_FINANCE;
