/*==============================================================================
  HOSPITAL 360 — Week 8: Snowflake Task DAG for Automated Pipeline Refresh

  Creates a task DAG that automates the Hospital 360 data pipeline:
    ROOT: TASK_REFRESH_PIPELINE  (daily CRON schedule, entry point)
      ├── TASK_REFRESH_MARTS     (re-populates 4 use-case marts)
      ├── TASK_RETRAIN_FORECAST  (AFTER marts — re-generates encounter forecast)
      ├── TASK_RETRAIN_ANOMALY   (AFTER marts — re-generates denial anomalies)
      └── TASK_LOG_PIPELINE_RUN  (AFTER all above — logs execution summary)

  All tasks are created in SUSPENDED state for demo safety.
  To run manually:  EXECUTE TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_PIPELINE;
  To enable daily:  ALTER TASK ... RESUME; (root task last, children first)
==============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE H360_XFM_WH;

-- =============================================================================
-- Stored Procedure: SP_REFRESH_MARTS
-- Truncates and repopulates all 4 use-case marts, logs results to monitoring
-- =============================================================================
CREATE OR REPLACE PROCEDURE HOSPITAL360_ML.MONITORING.SP_REFRESH_MARTS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET total_rows NUMBER := 0;
    LET mart_rows NUMBER := 0;

    -- UC1: Patient Leakage
    TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE;
    INSERT INTO HOSPITAL360_CUR.CLINICAL.MART_PATIENT_LEAKAGE
        (REFERRAL_ID, MRN, PATIENT_NAME, PATIENT_ZIP, PATIENT_PAYER_TYPE,
         REFERRING_PROVIDER_SK, REFERRING_PROVIDER, REFERRING_SPECIALTY,
         REFERRED_TO_NPI, REFERRED_TO_SPECIALTY,
         FACILITY_ID, FACILITY_NAME,
         REFERRAL_DATE, REFERRAL_MONTH, REFERRAL_QUARTER,
         STATUS, LEAKAGE_FLAG, EXPECTED_REVENUE, LOST_REVENUE,
         DAYS_SINCE_REFERRAL, IS_HIGH_VALUE)
    SELECT
        r.REFERRAL_ID, p.MRN,
        p.FIRST_NAME || ' ' || p.LAST_NAME, p.ZIP, py.PAYER_TYPE,
        r.REFERRING_PROVIDER_SK,
        prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL,
        prov.SPECIALTY, r.REFERRED_TO_NPI, r.REFERRED_TO_SPECIALTY,
        r.FACILITY_ID, f.FACILITY_NAME, r.REFERRAL_DATE,
        DATE_TRUNC('MONTH', r.REFERRAL_DATE),
        YEAR(r.REFERRAL_DATE)::STRING || '-Q' || QUARTER(r.REFERRAL_DATE)::STRING,
        r.STATUS, r.LEAKAGE_FLAG, r.EXPECTED_REVENUE,
        CASE WHEN r.LEAKAGE_FLAG THEN r.EXPECTED_REVENUE ELSE 0 END,
        DATEDIFF(DAY, r.REFERRAL_DATE, CURRENT_DATE()),
        r.EXPECTED_REVENUE > 5000
    FROM HOSPITAL360_CUR.CLINICAL.FCT_REFERRAL r
    JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT p ON p.PATIENT_SK = r.PATIENT_SK
    JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = r.REFERRING_PROVIDER_SK
    LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_ID = p.PRIMARY_PAYER_ID
    LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = r.FACILITY_ID;
    mart_rows := SQLROWCOUNT;
    total_rows := :total_rows + :mart_rows;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_MART_PATIENT_LEAKAGE', 'SUCCESS', :mart_rows,
            DATEDIFF(SECOND, :start_ts, CURRENT_TIMESTAMP()));

    -- UC2: Readmission & LOS
    LET start2 TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS;
    INSERT INTO HOSPITAL360_CUR.CLINICAL.MART_READMISSION_LOS
        (ENCOUNTER_ID, MRN, PATIENT_NAME, PATIENT_AGE, PATIENT_GENDER, HCC_SCORE,
         ADMIT_DATE, ADMIT_MONTH, DISCHARGE_DATE, DISCHARGE_DISPOSITION, ENCOUNTER_TYPE,
         LOS_DAYS, EXPECTED_LOS, LOS_VARIANCE, LOS_INDEX, IS_LONG_STAY,
         DRG_CODE, DRG_DESCRIPTION, DRG_WEIGHT, MDC_DESCRIPTION,
         READMIT_30_FLAG, PAYER_TYPE, PAYER_NAME,
         FACILITY_ID, FACILITY_NAME, DEPT_ID, DEPT_NAME,
         ATTENDING_PROVIDER, SPECIALTY,
         TOTAL_CHARGES, TOTAL_COST, TOTAL_PAYMENTS, COST_PER_DAY, NET_REVENUE)
    SELECT
        e.ENCOUNTER_ID, p.MRN,
        p.FIRST_NAME || ' ' || p.LAST_NAME, DATEDIFF(YEAR, p.DOB, e.ADMIT_DATE),
        p.GENDER, p.HCC_SCORE, e.ADMIT_DATE, DATE_TRUNC('MONTH', e.ADMIT_DATE),
        e.DISCHARGE_DATE, e.DISCHARGE_DISPOSITION, e.ENCOUNTER_TYPE, e.LOS_DAYS,
        COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS),
        e.LOS_DAYS - COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS),
        CASE WHEN COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 0
             THEN ROUND(e.LOS_DAYS / COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS), 2)
             ELSE NULL END,
        CASE WHEN COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 0
                  AND e.LOS_DAYS / COALESCE(drg.GEOMETRIC_LOS, e.EXPECTED_LOS) > 1.5
             THEN TRUE ELSE FALSE END,
        drg.DRG_CODE, drg.DESCRIPTION, drg.WEIGHT, drg.MDC_DESCRIPTION,
        e.READMIT_30_FLAG, py.PAYER_TYPE, py.PAYER_NAME,
        e.FACILITY_ID, f.FACILITY_NAME, e.DEPT_ID, d.DEPT_NAME,
        prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL,
        prov.SPECIALTY,
        e.TOTAL_CHARGES, e.TOTAL_COST, e.TOTAL_PAYMENTS,
        CASE WHEN e.LOS_DAYS > 0 THEN ROUND(e.TOTAL_COST / e.LOS_DAYS, 2) ELSE e.TOTAL_COST END,
        e.NET_REVENUE
    FROM HOSPITAL360_CUR.CLINICAL.FCT_ENCOUNTER e
    JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT p ON p.PATIENT_SK = e.PATIENT_SK
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = e.PROVIDER_SK
    LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_DRG drg ON drg.DRG_SK = e.DRG_SK
    LEFT JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_SK = e.PAYER_SK
    LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_DEPARTMENT d ON d.DEPT_ID = e.DEPT_ID
    LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = e.FACILITY_ID
    WHERE e.ENCOUNTER_TYPE IN ('INPATIENT', 'OBSERVATION');
    mart_rows := SQLROWCOUNT;
    total_rows := :total_rows + :mart_rows;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_MART_READMISSION_LOS', 'SUCCESS', :mart_rows,
            DATEDIFF(SECOND, :start2, CURRENT_TIMESTAMP()));

    -- UC3: OR Capacity
    LET start3 TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY;
    INSERT INTO HOSPITAL360_CUR.OPERATIONS.MART_OR_CAPACITY
        (CASE_ID, ENCOUNTER_ID, OR_ROOM_ID, FACILITY_ID, FACILITY_NAME,
         SURGEON_SK, SURGEON_NAME, SPECIALTY, BLOCK_NAME,
         CASE_DATE, CASE_MONTH, CASE_DAY_OF_WEEK,
         SCHEDULED_START, ACTUAL_START, ACTUAL_END,
         DELAY_MINUTES, CASE_MINUTES, TURNOVER_MINUTES, BLOCK_MINUTES,
         UTILIZATION_PCT, FIRST_CASE_ON_TIME, PRIME_TIME_FLAG,
         CASE_CLASS, ASA_CLASS, CPT_CODE, CPT_DESCRIPTION,
         IS_UNDERUTILIZED, IS_OVERTIME)
    SELECT
        orc.CASE_ID, orc.ENCOUNTER_ID, orc.OR_ROOM_ID, orc.FACILITY_ID,
        f.FACILITY_NAME, orc.SURGEON_SK,
        prov.FIRST_NAME || ' ' || prov.LAST_NAME || ', ' || prov.CREDENTIAL,
        prov.SPECIALTY, orc.BLOCK_NAME, orc.CASE_DATE,
        DATE_TRUNC('MONTH', orc.CASE_DATE), DAYNAME(orc.CASE_DATE),
        orc.SCHEDULED_START, orc.ACTUAL_START, orc.ACTUAL_END,
        DATEDIFF(MINUTE, orc.SCHEDULED_START, orc.ACTUAL_START),
        orc.CASE_MINUTES, orc.TURNOVER_MINUTES, orc.BLOCK_MINUTES,
        CASE WHEN orc.BLOCK_MINUTES > 0
             THEN ROUND(orc.CASE_MINUTES / orc.BLOCK_MINUTES, 3)
             ELSE NULL END,
        orc.FIRST_CASE_ON_TIME, orc.PRIME_TIME_FLAG,
        orc.CASE_CLASS, orc.ASA_CLASS, cpt.CPT_CODE, cpt.DESCRIPTION,
        CASE WHEN orc.BLOCK_MINUTES > 0 AND orc.CASE_MINUTES / orc.BLOCK_MINUTES < 0.60
             THEN TRUE ELSE FALSE END,
        CASE WHEN HOUR(orc.ACTUAL_END) >= 17 THEN TRUE ELSE FALSE END
    FROM HOSPITAL360_CUR.OPERATIONS.FCT_OR_CASE orc
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = orc.SURGEON_SK
    LEFT JOIN HOSPITAL360_CUR.OPERATIONS.DIM_FACILITY f ON f.FACILITY_ID = orc.FACILITY_ID
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROCEDURE_CPT cpt ON cpt.PROC_SK = orc.PRIMARY_CPT_SK;
    mart_rows := SQLROWCOUNT;
    total_rows := :total_rows + :mart_rows;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_MART_OR_CAPACITY', 'SUCCESS', :mart_rows,
            DATEDIFF(SECOND, :start3, CURRENT_TIMESTAMP()));

    -- UC4: Denials & RevCycle
    LET start4 TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    TRUNCATE TABLE IF EXISTS HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE;
    INSERT INTO HOSPITAL360_CUR.FINANCIAL.MART_DENIALS_REVCYCLE
        (CLAIM_LINE_SK, CLAIM_ID, LINE_NUMBER, ENCOUNTER_ID, MRN, PATIENT_NAME,
         PAYER_SK, PAYER_NAME, PAYER_TYPE, PROVIDER_NAME,
         SERVICE_DATE, SERVICE_MONTH, CHARGE_AMT, ALLOWED_AMT,
         DENIAL_REASON, DENIAL_CATEGORY, CLAIM_STATUS, IS_APPEALED, APPEAL_OUTCOME,
         CPT_CODE, CPT_DESCRIPTION, CPT_CATEGORY,
         ICD10_CODE, DX_DESCRIPTION,
         FILING_DATE, DAYS_TO_FILE, TIMELY_FILING_LIMIT, IS_TIMELY_FILED,
         ESTIMATED_RECOVERY)
    SELECT
        cl.CLAIM_LINE_SK, cl.CLAIM_ID, cl.LINE_NUMBER, cl.ENCOUNTER_ID,
        pt.MRN, pt.FIRST_NAME || ' ' || pt.LAST_NAME,
        cl.PAYER_SK, py.PAYER_NAME, py.PAYER_TYPE,
        prov.FIRST_NAME || ' ' || prov.LAST_NAME,
        cl.SERVICE_DATE, DATE_TRUNC('MONTH', cl.SERVICE_DATE),
        cl.CHARGE_AMT, cl.ALLOWED_AMT, cl.DENIAL_REASON,
        CASE
            WHEN cl.DENIAL_REASON = 'ELIGIBILITY'      THEN 'ELIGIBILITY & ENROLLMENT'
            WHEN cl.DENIAL_REASON = 'AUTH_REQUIRED'     THEN 'PRIOR AUTHORIZATION'
            WHEN cl.DENIAL_REASON = 'CODING_ERROR'      THEN 'CODING & BILLING'
            WHEN cl.DENIAL_REASON = 'MEDICAL_NECESSITY' THEN 'CLINICAL / MEDICAL NECESSITY'
            ELSE 'OTHER'
        END,
        cl.CLAIM_STATUS, cl.CLAIM_STATUS = 'APPEALED',
        CASE
            WHEN cl.CLAIM_STATUS = 'APPEALED' AND ABS(MOD(HASH(cl.CLAIM_ID), 100)) < 40 THEN 'WON'
            WHEN cl.CLAIM_STATUS = 'APPEALED' THEN 'LOST'
            WHEN cl.CLAIM_STATUS = 'DENIED' THEN 'NOT_APPEALED'
            ELSE 'PENDING'
        END,
        cpt.CPT_CODE, cpt.DESCRIPTION, cpt.CATEGORY,
        dx.ICD10_CODE, dx.DESCRIPTION,
        cl.FILING_DATE, DATEDIFF(DAY, cl.SERVICE_DATE, cl.FILING_DATE),
        py.TIMELY_FILING_DAYS,
        CASE WHEN py.TIMELY_FILING_DAYS IS NOT NULL
                  AND DATEDIFF(DAY, cl.SERVICE_DATE, cl.FILING_DATE) <= py.TIMELY_FILING_DAYS
             THEN TRUE ELSE FALSE END,
        ROUND(cl.CHARGE_AMT * CASE
            WHEN cl.DENIAL_REASON = 'ELIGIBILITY'      THEN 0.30
            WHEN cl.DENIAL_REASON = 'AUTH_REQUIRED'     THEN 0.50
            WHEN cl.DENIAL_REASON = 'CODING_ERROR'      THEN 0.65
            WHEN cl.DENIAL_REASON = 'MEDICAL_NECESSITY' THEN 0.35
            ELSE 0.20
        END, 2)
    FROM HOSPITAL360_CUR.FINANCIAL.FCT_CLAIM_LINE cl
    JOIN HOSPITAL360_CUR.CLINICAL.DIM_PATIENT pt ON pt.PATIENT_SK = cl.PATIENT_SK
    JOIN HOSPITAL360_CUR.FINANCIAL.DIM_PAYER py ON py.PAYER_SK = cl.PAYER_SK
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROVIDER prov ON prov.PROVIDER_SK = cl.PROVIDER_SK
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_PROCEDURE_CPT cpt ON cpt.PROC_SK = cl.PROC_SK
    LEFT JOIN HOSPITAL360_CUR.CLINICAL.DIM_DIAGNOSIS_ICD10 dx ON dx.DX_SK = cl.DX_SK
    WHERE cl.DENIED_FLAG = TRUE;
    mart_rows := SQLROWCOUNT;
    total_rows := :total_rows + :mart_rows;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_MART_DENIALS_REVCYCLE', 'SUCCESS', :mart_rows,
            DATEDIFF(SECOND, :start4, CURRENT_TIMESTAMP()));

    RETURN 'Mart refresh complete. Total rows: ' || :total_rows::STRING;
END;

-- =============================================================================
-- Stored Procedure: SP_REFRESH_FORECAST
-- Re-generates the encounter volume forecast predictions
-- =============================================================================
CREATE OR REPLACE PROCEDURE HOSPITAL360_ML.MONITORING.SP_REFRESH_FORECAST()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();

    CREATE OR REPLACE TABLE HOSPITAL360_ML.PREDICTIONS.PRED_ENCOUNTER_VOLUME AS
    SELECT
        SERIES::VARCHAR          AS ENCOUNTER_TYPE,
        TS::TIMESTAMP_NTZ        AS FORECAST_DATE,
        ROUND(FORECAST, 0)       AS FORECAST_COUNT,
        ROUND(LOWER_BOUND, 0)    AS LOWER_BOUND,
        ROUND(UPPER_BOUND, 0)    AS UPPER_BOUND,
        CURRENT_TIMESTAMP()      AS MODEL_RUN_TS
    FROM TABLE(HOSPITAL360_ML.MODELS.FORECAST_ENCOUNTER_VOLUME!FORECAST(
        FORECASTING_PERIODS => 90
    ));

    LET row_count NUMBER := SQLROWCOUNT;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_FORECAST', 'SUCCESS', :row_count,
            DATEDIFF(SECOND, :start_ts, CURRENT_TIMESTAMP()));

    -- Log model performance metric (forecast coverage)
    INSERT INTO HOSPITAL360_ML.MONITORING.MODEL_PERFORMANCE_LOG (MODEL_NAME, METRIC_NAME, METRIC_VALUE)
    VALUES ('FORECAST_ENCOUNTER_VOLUME', 'PREDICTION_COUNT', :row_count);

    RETURN 'Forecast refresh complete. Rows: ' || :row_count::STRING;
END;

-- =============================================================================
-- Stored Procedure: SP_REFRESH_ANOMALY
-- Re-generates the denial anomaly detection predictions
-- =============================================================================
CREATE OR REPLACE PROCEDURE HOSPITAL360_ML.MONITORING.SP_REFRESH_ANOMALY()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();

    -- Materialize recent 6 months for anomaly detection
    CREATE OR REPLACE TEMPORARY TABLE HOSPITAL360_ML.FEATURES.TMP_RECENT_DENIALS AS
    SELECT TS, DENIAL_CATEGORY, DENIAL_COUNT
    FROM HOSPITAL360_ML.FEATURES.VW_DAILY_DENIAL_VOLUME
    WHERE TS >= DATEADD(MONTH, -6, (SELECT MAX(TS) FROM HOSPITAL360_ML.FEATURES.VW_DAILY_DENIAL_VOLUME));

    -- Run anomaly detection and join actuals
    CREATE OR REPLACE TABLE HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES AS
    SELECT
        r.SERIES::VARCHAR           AS DENIAL_CATEGORY,
        r.TS::TIMESTAMP_NTZ         AS TS,
        ROUND(r.FORECAST, 0)        AS EXPECTED_COUNT,
        ROUND(r.LOWER_BOUND, 0)     AS LOWER_BOUND,
        ROUND(r.UPPER_BOUND, 0)     AS UPPER_BOUND,
        r.IS_ANOMALY::BOOLEAN       AS IS_ANOMALY,
        ROUND(r.PERCENTILE, 4)      AS PERCENTILE,
        d.DENIAL_COUNT              AS ACTUAL_COUNT,
        d.DENIED_CHARGES            AS ACTUAL_CHARGES,
        CURRENT_TIMESTAMP()         AS MODEL_RUN_TS
    FROM TABLE(HOSPITAL360_ML.MODELS.ANOMALY_DENIAL_VOLUME!DETECT_ANOMALIES(
        INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'HOSPITAL360_ML.FEATURES.TMP_RECENT_DENIALS'),
        SERIES_COLNAME => 'DENIAL_CATEGORY',
        TIMESTAMP_COLNAME => 'TS',
        TARGET_COLNAME => 'DENIAL_COUNT'
    )) r
    LEFT JOIN HOSPITAL360_ML.FEATURES.VW_DAILY_DENIAL_VOLUME d
        ON r.SERIES = d.DENIAL_CATEGORY AND r.TS = d.TS;

    LET row_count NUMBER := SQLROWCOUNT;
    LET anomaly_count NUMBER := 0;

    SELECT COUNT(*) INTO :anomaly_count
    FROM HOSPITAL360_ML.PREDICTIONS.PRED_DENIAL_ANOMALIES
    WHERE IS_ANOMALY = TRUE;

    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS)
    VALUES ('REFRESH_ANOMALY_DETECTION', 'SUCCESS', :row_count,
            DATEDIFF(SECOND, :start_ts, CURRENT_TIMESTAMP()));

    -- Log anomaly count as performance metric
    INSERT INTO HOSPITAL360_ML.MONITORING.MODEL_PERFORMANCE_LOG (MODEL_NAME, METRIC_NAME, METRIC_VALUE)
    VALUES ('ANOMALY_DENIAL_VOLUME', 'ANOMALY_COUNT', :anomaly_count);

    INSERT INTO HOSPITAL360_ML.MONITORING.MODEL_PERFORMANCE_LOG (MODEL_NAME, METRIC_NAME, METRIC_VALUE)
    VALUES ('ANOMALY_DENIAL_VOLUME', 'TOTAL_OBSERVATIONS', :row_count);

    RETURN 'Anomaly detection refresh complete. Rows: ' || :row_count::STRING || ', Anomalies: ' || :anomaly_count::STRING;
END;

-- =============================================================================
-- Task DAG Definition
-- =============================================================================

-- Root task: daily at 6 AM UTC (suspended for demo safety)
CREATE OR REPLACE TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_PIPELINE
    WAREHOUSE = H360_XFM_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
    COMMENT = 'Hospital 360 daily pipeline refresh — root task (resume to enable)'
AS
    SELECT 1;  -- Root task is a no-op trigger; children do the work

-- Child 1: Refresh all 4 marts
CREATE OR REPLACE TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_MARTS
    WAREHOUSE = H360_XFM_WH
    AFTER HOSPITAL360_ML.MONITORING.TASK_REFRESH_PIPELINE
    COMMENT = 'Truncate + rebuild all 4 use-case marts from fact/dim tables'
AS
    CALL HOSPITAL360_ML.MONITORING.SP_REFRESH_MARTS();

-- Child 2: Regenerate forecast predictions (after marts)
CREATE OR REPLACE TASK HOSPITAL360_ML.MONITORING.TASK_RETRAIN_FORECAST
    WAREHOUSE = H360_ML_WH
    AFTER HOSPITAL360_ML.MONITORING.TASK_REFRESH_MARTS
    COMMENT = 'Regenerate 90-day encounter volume forecast from trained model'
AS
    CALL HOSPITAL360_ML.MONITORING.SP_REFRESH_FORECAST();

-- Child 3: Regenerate anomaly detection predictions (after marts)
CREATE OR REPLACE TASK HOSPITAL360_ML.MONITORING.TASK_RETRAIN_ANOMALY
    WAREHOUSE = H360_ML_WH
    AFTER HOSPITAL360_ML.MONITORING.TASK_REFRESH_MARTS
    COMMENT = 'Regenerate denial anomaly detection from trained model'
AS
    CALL HOSPITAL360_ML.MONITORING.SP_REFRESH_ANOMALY();

-- Child 4: Log pipeline completion summary
CREATE OR REPLACE TASK HOSPITAL360_ML.MONITORING.TASK_LOG_PIPELINE_RUN
    WAREHOUSE = H360_BI_WH
    AFTER HOSPITAL360_ML.MONITORING.TASK_RETRAIN_FORECAST,
          HOSPITAL360_ML.MONITORING.TASK_RETRAIN_ANOMALY
    COMMENT = 'Logs overall pipeline completion to monitoring table'
AS
    INSERT INTO HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG
        (TASK_NAME, STATUS, ROWS_AFFECTED, DURATION_SECONDS, METADATA)
    SELECT 'PIPELINE_COMPLETE', 'SUCCESS',
           (SELECT SUM(ROWS_AFFECTED) FROM HOSPITAL360_ML.MONITORING.PIPELINE_RUN_LOG
            WHERE RUN_TS >= DATEADD(MINUTE, -30, CURRENT_TIMESTAMP())
              AND TASK_NAME != 'PIPELINE_COMPLETE'),
           NULL,
           OBJECT_CONSTRUCT('completed_at', CURRENT_TIMESTAMP()::STRING,
                            'task_count', 4);

-- =============================================================================
-- Note: All tasks are created in SUSPENDED state by default.
-- To run the full pipeline once:
--   EXECUTE TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_PIPELINE;
--
-- To enable the daily schedule:
--   ALTER TASK HOSPITAL360_ML.MONITORING.TASK_LOG_PIPELINE_RUN RESUME;
--   ALTER TASK HOSPITAL360_ML.MONITORING.TASK_RETRAIN_FORECAST RESUME;
--   ALTER TASK HOSPITAL360_ML.MONITORING.TASK_RETRAIN_ANOMALY RESUME;
--   ALTER TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_MARTS RESUME;
--   ALTER TASK HOSPITAL360_ML.MONITORING.TASK_REFRESH_PIPELINE RESUME;
-- =============================================================================

-- Grant MONITOR on tasks to analyst/admin roles
GRANT MONITOR ON ALL TASKS IN SCHEMA HOSPITAL360_ML.MONITORING TO ROLE H360_ANALYST;
GRANT MONITOR ON ALL TASKS IN SCHEMA HOSPITAL360_ML.MONITORING TO ROLE H360_EXEC;
