import KPICard from '../components/KPICard';
import DataTable from '../components/DataTable';
import { useSnowflakeQuery } from '../hooks/useSnowflakeQuery';

export default function OpsMonitor() {
  const encounters = useSnowflakeQuery(
    'ops-encounters',
    `SELECT COUNT(*) AS N FROM HOSPITAL_360.CLINICAL.FCT_ENCOUNTER`
  );
  const patients = useSnowflakeQuery(
    'ops-patients',
    `SELECT COUNT(*) AS N FROM HOSPITAL_360.CLINICAL.DIM_PATIENT`
  );
  const providers = useSnowflakeQuery(
    'ops-providers',
    `SELECT COUNT(*) AS N FROM HOSPITAL_360.CLINICAL.DIM_PROVIDER`
  );
  const predictions = useSnowflakeQuery(
    'ops-predictions',
    `SELECT COUNT(*) AS N FROM HOSPITAL_360.ML_PREDICTIONS.PRED_ENCOUNTER_VOLUME`
  );
  const anomalies = useSnowflakeQuery(
    'ops-anomalies',
    `SELECT COUNT(*) AS N FROM HOSPITAL_360.ML_PREDICTIONS.PRED_ANOMALY_DETECTION`
  );

  const predTables = useSnowflakeQuery(
    'ops-pred-tables',
    `SELECT TABLE_NAME, ROW_COUNT, BYTES, LAST_ALTERED
    FROM HOSPITAL_360.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'ML_PREDICTIONS'
    ORDER BY TABLE_NAME`
  );

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">Ops Monitor</h1>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        <KPICard title="Encounters" value={encounters.data?.[0]?.N?.toLocaleString()} isLoading={encounters.isLoading} tooltip="Encounters — total row count in the fact encounter table, representing all patient visits ingested into the platform" />
        <KPICard title="Patients" value={patients.data?.[0]?.N?.toLocaleString()} isLoading={patients.isLoading} tooltip="Patients — total unique patients in the patient dimension table across all facilities" />
        <KPICard title="Providers" value={providers.data?.[0]?.N?.toLocaleString()} isLoading={providers.isLoading} tooltip="Providers — total unique providers (physicians, NPs, PAs) registered in the provider dimension" />
        <KPICard title="Predictions" value={predictions.data?.[0]?.N?.toLocaleString()} isLoading={predictions.isLoading} tooltip="Predictions — total rows in the encounter volume forecast table generated by Cortex ML" />
        <KPICard title="Anomaly Records" value={anomalies.data?.[0]?.N?.toLocaleString()} isLoading={anomalies.isLoading} tooltip="Anomaly Records — total rows produced by the anomaly detection model, flagging unusual patterns in denial volumes" />
      </div>

      <section>
        <h2 className="text-lg font-semibold text-gray-900 mb-3">Prediction Tables</h2>
        {predTables.isLoading ? (
          <div className="text-gray-600 text-sm">Loading...</div>
        ) : predTables.data ? (
          <DataTable
            columns={[
              { key: 'TABLE_NAME', label: 'Table' },
              { key: 'ROW_COUNT', label: 'Rows' },
              { key: 'BYTES', label: 'Bytes' },
              { key: 'LAST_ALTERED', label: 'Last Altered' },
            ]}
            data={predTables.data}
          />
        ) : null}
      </section>
    </div>
  );
}
